# 🛸 Generated by zPy
from typing import Any

from zpy.app.usecase import UseCase


from ..domain.repositories import CustomersRepository


class customer_list(UseCase[Any, Any]):
    """
        Use Case description.
    """

    def __init__(self, repository: CustomersRepository) -> None:
        self.repository = repository

    def execute(self, data: Any, *args, **kwargs) -> None:
        # TODO Do magic with business rules 😁
        return self.repository.customer_list(data)