# 🛸 Generated by zPy
from typing import Any
from zpy.app.usecase import UseCase
from ..domain.repositories import CustomersRepository
from zpy.api.http.errors import BadRequest
from ..domain.objects import name,email
from ..domain.requests import CustomerRequest


class customer_add(UseCase[Any, Any]):
    """
        Use Case description.
    """

    def __init__(self, repository: CustomersRepository) -> None:
        self.repository = repository

    def execute(self, data: CustomerRequest, *args, **kwargs) -> None:
        try:
            print("Inician validaciones")
            name(data.name)
            email(data.email)            
            res = self.repository.customer_add(data)
        except Exception as e:
            msg  = str(e.message)
            raise BadRequest(message=msg)

        return res