# 🛸 Generated by zPy
# 🛰 Application Layer

from .application.customer_list import customer_list

# 📦  Domain Layer

from .domain.repositories import CustomersRepository


# Infrastructure

from .infraestructure.customers_repository import AwesomeCustomersRepository