# 🛸 Generated by zPy
from di import customer_list_uc
from flask import Flask
from zpy.api.http.response import response_builder
from zpy.api.flask import create_app
from src.contexts.customers.domain.responses import CustomerResponse


app: Flask = create_app()


@app.route("/customers", methods=["GET"])
@response_builder()
def awesome_api():
    return CustomerResponse(**customer_list_uc.execute(None))