# 🛸 Generated by zPy
from di import customer_list_uc,customer_detail_uc,customer_add_uc
from flask import Flask,request
from zpy.api.flask import create_app
from zpy.api.http.response import response_builder, SuccessResponse, HttpStatus
from zpy.api.http.request import parse_request
from src.contexts.customers.domain.responses import CustomersResponse
from src.contexts.customers.domain.requests import CustomerRequest


app: Flask = create_app()


@app.route("/customers", methods=["GET"])
@response_builder()
def get_customers():
    return CustomersResponse(**customer_list_uc.execute(None))

@app.route("/customers/<cus_id>", methods=["GET"])
@response_builder()
def get_customers_by_id(cus_id:str):
    return CustomersResponse(**customer_detail_uc.execute(cus_id))

@app.route("/customers/add", methods=["PATCH"])
@response_builder()
def add_customers():
    cus, _  = parse_request(request.json, CustomerRequest)
    customer_add_uc.execute(cus)
    return SuccessResponse.empty(HttpStatus.SUCCESS)    