# 🛸 Generated by zPy
from di import customer_list_uc,customer_detail_uc,customer_add_uc,customer_update_uc,customer_delete_uc
from flask import Flask,request
from zpy.api.flask import create_app
from zpy.api.http.response import response_builder, SuccessResponse, HttpStatus
from zpy.api.http.request import parse_request
from src.contexts.customers.domain.responses import CustomersResponse
from src.contexts.customers.domain.requests import CustomerRequest


app: Flask = create_app()


@app.route("/customers", methods=["GET"])
@response_builder()
def get_customers():
    return CustomersResponse(**customer_list_uc.execute(None))

@app.route("/customers/<cus_id>", methods=["GET"])
@response_builder()
def get_customers_by_id(cus_id:str):
    return CustomersResponse(**customer_detail_uc.execute(cus_id))

@app.route("/customers/add", methods=["POST"])
@response_builder()
def add_customers():
    cus, _  = parse_request(request.json, CustomerRequest)
    #customer_add_uc.execute(cus)
    return CustomersResponse(**customer_add_uc.execute(cus))  

@app.route("/customers/<cus_id>", methods=["PATCH"])
@response_builder()
def update_customers(cus_id:str):
    cus, _  = parse_request(request.json, CustomerRequest)
    cus.id = cus_id
    customer_update_uc.execute(cus)
    return SuccessResponse.empty(HttpStatus.SUCCESS)   

@app.route("/customers/<cus_id>", methods=["DELETE"])
@response_builder()
def delete_customers_by_id(cus_id:str):
    customer_delete_uc.execute(cus_id)
    return SuccessResponse.empty(HttpStatus.SUCCESS) 