# 🛸 Generated by zPy
from zpy.utils import get_env_or_throw as var
from zpy.app.usecase import UseCase
from typing import Any

# * Setup Dependencies 📃
from contexts.customers.domain.repositories import CustomersRepository
from contexts.customers.infraestructure.customers_repository import AwesomeCustomersRepository
from contexts.customers.application.customer_list import customer_list

repository: CustomersRepository = AwesomeCustomersRepository()


# Setup UseCases

customer_list_uc: UseCase[Any, None] = customer_list(repository)
print("🚀 Dependencies loaded successfully...")