# 🛸 Generated by zPy
from typing import Any
from zpy.api.flask.cloud_handlers import aws_lambda

from api.routes import app
import aws_lambda_wsgi as awsgi


@aws_lambda()
def handle(event: dict, context: dict) -> Any:
    return awsgi.response(app, event, context)