# 🛸 Generated by zPy
from ..domain.repositories import CustomersRepository
from ..domain.requests import CustomerRequest
from typing import Any
import json
import uuid

class AwesomeCustomersRepository(CustomersRepository):

    def __init__(self):
        ...

    def customer_list(self, data: Any) -> Any:
        try:
            f = open('data.json')
            data = json.load(f)
            f.close()
            customers = {"customers":data}
            return customers
        finally:
            ...

    def customer_detail(self, cus_id: Any) -> Any:
        try:
            f = open('data.json')
            data = json.load(f)
            f.close()
            cus = []            
            for item in data:
                if item['id'] == cus_id:                                   
                    cus.append(item)                    
            customers = {"customers":cus}            
            return customers
        finally:
            ...

    def customer_add(self, cus: CustomerRequest) -> Any:
        try:
            f = open('data.json')
            data = json.load(f)   
            f.close()         
            item = {"id": str(uuid.uuid1()),"name":cus.name,"email":cus.email}
            data.append(item)
            
            with open('data.json', 'w') as json_file:
                json.dump(data, json_file)
           
            return 'ok'
        finally:
            ...
    