# 🛸 Generated by zPy
from ..domain.repositories import CustomersRepository
from typing import Any
import json

class AwesomeCustomersRepository(CustomersRepository):

    def __init__(self):
        ...

    def customer_list(self, data: Any) -> Any:
        try:
            f = open('data.json')
            data = json.load(f)
            f.close()
            customers = {"customers":data}
            return customers
        finally:
            ...

    def customer_detail(self, cus_id: Any) -> Any:
        try:
            f = open('data.json')
            data = json.load(f)
            f.close()
            cus = []            
            for item in data:
                if item['id'] == cus_id:                                   
                    cus.append(item)                    
            customers = {"customers":cus}            
            return customers
        finally:
            ...


    